### ISSUE TITLE
段错误 (核心已转储)

### ISSUE THREAD

**Issue by wh277** [ZhonghuiGu/HEAL#4]
您好，我在安装"fair-esm[esmfold]"和'dllogger @ git+https://github.com/NVIDIA/dllogger.git'后运行predictor.py，直接报错“段错误 (核心已转储)”，没有其它任何文字。试过安装'openfold @ git+https://github.com/aqlaboratory/openfold.git@4b41059694619831a7db195b7e0988fc4ff3a307'，但安装失败，  “RuntimeError: Error compiling objects for extension  ERROR: Failed building wheel for openfold”。
![image](https://github.com/ZhonghuiGu/HEAL/assets/125532384/8b600296-e800-4115-8687-de43fba69c5e)

**Comment by ZhonghuiGu** [comment]
I think there's no need to install ESMFold, just installing ESM is enough.

**Comment by wh277** [comment]
ok,thanks
