### ISSUE TITLE
Missing file: args.esm1b_model --contact- regression.pt

### ISSUE THREAD

**Issue by MiJia-ID** [ZhonghuiGu/HEAL#6]
Hello,I run predictor.py with esm_model, alphabet = esm.pretrained.load_model_and_alphabet_local(args.esm1b_model) reporting error can't find args.esm1b_model --contact- regression.pt, do I need to enter additional weights?

**Comment by ZhonghuiGu** [comment]
You can download esm1b_t33_650M_UR50S-contact-regression.pt from ESM repository under the same dir with esm1b_t33_650M_UR50S.pt, or change the code of ESM package. The former solution is easier.

**Comment by MiJia-ID** [comment]
Thank you very much for your reply, I'm also experiencing problems with the processed.zip prompting for null after downloading it!

**Comment by MiJia-ID** [comment]
Thank you very much for your reply, I'm also experiencing problems with the ‘processed.zip‘(datasets)prompting for null after downloading it!

**Comment by MiJia-ID** [comment]
Thank you very much for your reply

**Comment by ZhonghuiGu** [comment]
The link for dataset downloading can be visited now.
